import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.database.session import SessionLocal
from app.models.audit import AuditLogModel
from app.models.models import UserModel

client = TestClient(app)

@pytest.fixture(autouse=True)
def clean_db():
    db = SessionLocal()
    db.query(AuditLogModel).delete()
    db.query(UserModel).delete()
    db.commit()
    db.close()

def test_enterprise_audit_log_capture():
    # 1. Trigger registration operation (mutation)
    reg_payload = {"username": "auditor_user", "password": "securepassword", "role": "Auditor"}
    res = client.post("/api/v1/auth/register", json=reg_payload)
    assert res.status_code == 201

    # 2. Query database directly to confirm audit log was generated by middleware
    db = SessionLocal()
    try:
        logs = db.query(AuditLogModel).all()
        assert len(logs) == 1
        audit_entry = logs[0]
        assert audit_entry.action == "User Creation"
        assert "/auth/register" in audit_entry.resource
        assert audit_entry.ip_address is not None
    finally:
        db.close()

    # 3. Retrieve auth token to request audit logs API
    login_res = client.post("/api/v1/auth/login", json={"username": "auditor_user", "password": "securepassword"})
    token = login_res.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}

    # 4. Fetch list of audit logs via API
    api_res = client.get("/api/v1/audit/", headers=headers)
    assert api_res.status_code == 200
    res_data = api_res.json()
    # There should be logs for registration, login, etc.
    assert len(res_data) >= 1
