"""Initial schema migration

Revision ID: f8b2a9662a68
Revises: 
Create Date: 2026-07-21 07:16:48.908876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b2a9662a68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_blacklisted_tokens_token'), 'blacklisted_tokens', ['token'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('chunks', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('failed_asset', sa.String(length=100), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('graph_snapshot', sa.JSON(), nullable=True),
    sa.Column('simulation_data', sa.JSON(), nullable=True),
    sa.Column('decision_data', sa.JSON(), nullable=True),
    sa.Column('runbook_history', sa.JSON(), nullable=True),
    sa.Column('technician_feedback', sa.JSON(), nullable=True),
    sa.Column('regenerated_runbooks', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incidents_failed_asset'), 'incidents', ['failed_asset'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=False)
    op.create_table('runbooks',
    sa.Column('runbook_id', sa.String(length=100), nullable=False),
    sa.Column('failed_asset', sa.String(length=100), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_regenerated', sa.Boolean(), nullable=True),
    sa.Column('update_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('runbook_id')
    )
    op.create_index(op.f('ix_runbooks_runbook_id'), 'runbooks', ['runbook_id'], unique=False)
    op.create_table('simulations',
    sa.Column('simulation_id', sa.String(length=100), nullable=False),
    sa.Column('failed_asset', sa.String(length=100), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('scenarios', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_index(op.f('ix_simulations_simulation_id'), 'simulations', ['simulation_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('current_session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_simulations_simulation_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_runbooks_runbook_id'), table_name='runbooks')
    op.drop_table('runbooks')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_failed_asset'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_blacklisted_tokens_token'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
